### PR TITLE
fix(angryjet): support pointers to structs

### LINKED ISSUE #112: Angryjet doesn't support pointer structs
### What happened?

We've recently adopted https://github.com/kubernetes-sigs/kube-api-linter to perform linting on our provider's types.

All of the recommendations/changes it makes are straight forward and compatible with Angryjet code generation, however there is one recommendation that prevents code generation from working for a managed resource.

For example, given this MR:

```
type MyType struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MyTypeSpec   `json:"spec"`
	Status MyTypeStatus `json:"status,omitempty"`
}
```

It will enforce that the struct looks like the following:

```
type MyType struct {
	metav1.TypeMeta   `json:",inline"`
	// metadata is the standard object metadata
	// +kubebuilder:validation:Optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// spec defines the desired state of MyType
	// +kubebuilder:validation:Required
	Spec   MyTypeSpec   `json:"spec"`

	// status defines the observed state of MyType
	// +kubebuilder:validation:Optional
	Status *MyTypeStatus `json:"status,omitempty"`
}
```

The main issue is with `Status *MyTypeStatus `json:"status,omitempty"``

As it is optional, kubeapilinter expects the Status to be a pointer to a struct.

I've found angryjet doesn't support generating code if this is the case.

### How can we reproduce it?
Use angryjet to generate methodsets for the above struct

### What environment did it happen in?
https://github.com/crossplane/crossplane-tools/commit/889cfb10051739efb9e4cf79950524d43767d54c

### PR DESCRIPTION
**Pull request by awprice**
### Description of your changes

Add support for pointers to structs in `findStruct`

Fixes #112 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Tested generation with existing provider APIs, found no change in resulting generated code.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: internal/fields/fields.go [hunk 1]
```diff
@@ -93,12 +93,8 @@ func findStruct(o types.Object) *types.Struct {
 	case *types.Struct:
 		return t
 	case *types.Slice:
-		s, ok := t.Elem().Underlying().(*types.Struct)
-		if !ok {
-			return nil
-		}
-		return s
```
Comment (negz) [inline internal/fields/fields.go:100]: Was removing this block intentional? Could you explain why?

Comment (negz) [reply internal/fields/fields.go]: Phew, glad I asked haha. I'm very rusty on this code so I almost assumed it was fine. 😆
